export const paintings = {
    0: {
        "smallImg": '/images/0.jpg',
        "name": "Bite",
        "images": ['/images/0.jpg', '/images/1.jpg', '/images/2.jpg'],
        "descr": "Proin erat urna, tincidunt in gravida at, blandit sed quam. Proin erat urna, tincidunt in gravida at, blandit sed quam. Proin erat urna, tincidunt in gravida at, blandit sed quam. Proin erat urna, tincidunt in gravida at, blandit sed quam. Proin erat urna, tincidunt in gravida at, blandit sed quam. Proin erat urna, tincidunt in gravida at, blandit sed quam. Proin erat urna, tincidunt in gravida at, blandit sed quam. Proin erat urna, tincidunt in gravida at, blandit sed quam. Proin erat urna, tincidunt in gravida at, blandit sed quam. Proin erat urna, tincidunt in gravida at, blandit sed quam. Proin erat urna, tincidunt in gravida at, blandit sed quam.",
    },
    1: {
        "smallImg": '/images/1.jpg',
        "name": "Poil",
        "images": ['/images/1.jpg'],
        "descr": "Donec mollis tellus sed enim ultricies, et imperdiet lacus cursus.",
    },
    2: {
        "smallImg": '/images/2.jpg',
        "name": "Caca",
        "images": ['/images/2.jpg'],
        "descr": "Nullam venenatis maximus metus, sed consequat augue auctor imperdiet.",
    },
    3: {
        "smallImg": '/images/3.jpg',
        "name": "Boudin",
        "images": ['/images/3.jpg'],
        "descr": "Fusce ac efficitur odio, non scelerisque odio.",
    },
    4: {
        "smallImg": '/images/4.jpg',
        "name": "Saucisse",
        "images": ['/images/4.jpg'],
        "descr": "Etiam sit amet ligula facilisis lacus iaculis condimentum.",
    },
    5: {
        "smallImg": '/images/5.jpg',
        "name": "Mitraillette",
        "images": ['/images/5.jpg'],
        "descr": "",
    },
    6: {
        "smallImg": '/images/6.jpg',
        "name": "Durum",
        "images": ['/images/6.jpg'],
        "descr": "",
    },
    7: {
        "smallImg": '/images/7.jpg',
        "name": "Paté",
        "images": ['/images/7.jpg'],
        "descr": "",
    },
    8: {
        "smallImg": '/images/0.jpg',
        "name": "Bite",
        "images": ['/images/0.jpg'],
        "descr": "Proin erat urna, tincidunt in gravida at, blandit sed quam.",
    },
    9: {
        "smallImg": '/images/1.jpg',
        "name": "Poil",
        "images": ['/images/1.jpg'],
        "descr": "Donec mollis tellus sed enim ultricies, et imperdiet lacus cursus.",
    },
    10: {
        "smallImg": '/images/2.jpg',
        "name": "Caca",
        "images": ['/images/2.jpg'],
        "descr": "Nullam venenatis maximus metus, sed consequat augue auctor imperdiet.",
    },
    11: {
        "smallImg": '/images/3.jpg',
        "name": "Boudin",
        "images": ['/images/3.jpg'],
        "descr": "Fusce ac efficitur odio, non scelerisque odio.",
    },
    12: {
        "smallImg": '/images/4.jpg',
        "name": "Saucisse",
        "images": ['/images/4.jpg'],
        "descr": "Etiam sit amet ligula facilisis lacus iaculis condimentum.",
    },
    13: {
        "smallImg": '/images/5.jpg',
        "name": "Mitraillette",
        "images": ['/images/5.jpg'],
        "descr": "",
    },
    14: {
        "smallImg": '/images/6.jpg',
        "name": "Durum",
        "images": ['/images/6.jpg'],
        "descr": "",
    },
    15: {
        "smallImg": '/images/7.jpg',
        "name": "Paté",
        "images": ['/images/7.jpg'],
        "descr": "",
    },
    16: {
        "smallImg": '/images/0.jpg',
        "name": "Bite",
        "images": ['/images/0.jpg'],
        "descr": "Proin erat urna, tincidunt in gravida at, blandit sed quam.",
    },
    17: {
        "smallImg": '/images/1.jpg',
        "name": "Poil",
        "images": ['/images/1.jpg'],
        "descr": "Donec mollis tellus sed enim ultricies, et imperdiet lacus cursus.",
    },
    18: {
        "smallImg": '/images/2.jpg',
        "name": "Caca",
        "images": ['/images/2.jpg'],
        "descr": "Nullam venenatis maximus metus, sed consequat augue auctor imperdiet.",
    },
    19: {
        "smallImg": '/images/3.jpg',
        "name": "Boudin",
        "images": ['/images/3.jpg'],
        "descr": "Fusce ac efficitur odio, non scelerisque odio.",
    },
    20: {
        "smallImg": '/images/4.jpg',
        "name": "Saucisse",
        "images": ['/images/4.jpg'],
        "descr": "Etiam sit amet ligula facilisis lacus iaculis condimentum.",
    },
    21: {
        "smallImg": '/images/5.jpg',
        "name": "Mitraillette",
        "images": ['/images/5.jpg'],
        "descr": "",
    },
    22: {
        "smallImg": '/images/6.jpg',
        "name": "Durum",
        "images": ['/images/6.jpg'],
        "descr": "",
    },
    23: {
        "smallImg": '/images/7.jpg',
        "name": "Paté",
        "images": ['/images/7.jpg'],
        "descr": "",
    },
    24: {
        "smallImg": '/images/0.jpg',
        "name": "Bite",
        "images": ['/images/0.jpg'],
        "descr": "Proin erat urna, tincidunt in gravida at, blandit sed quam.",
    },
    25: {
        "smallImg": '/images/1.jpg',
        "name": "Poil",
        "images": ['/images/1.jpg'],
        "descr": "Donec mollis tellus sed enim ultricies, et imperdiet lacus cursus.",
    },
    26: {
        "smallImg": '/images/2.jpg',
        "name": "Caca",
        "images": ['/images/2.jpg'],
        "descr": "Nullam venenatis maximus metus, sed consequat augue auctor imperdiet.",
    },
    27: {
        "smallImg": '/images/3.jpg',
        "name": "Boudin",
        "images": ['/images/3.jpg'],
        "descr": "Fusce ac efficitur odio, non scelerisque odio.",
    },
    28: {
        "smallImg": '/images/4.jpg',
        "name": "Saucisse",
        "images": ['/images/4.jpg'],
        "descr": "Etiam sit amet ligula facilisis lacus iaculis condimentum.",
    },
    29: {
        "smallImg": '/images/5.jpg',
        "name": "Mitraillette",
        "images": ['/images/5.jpg'],
        "descr": "",
    },
    30: {
        "smallImg": '/images/6.jpg',
        "name": "Durum",
        "images": ['/images/6.jpg'],
        "descr": "",
    },
    31: {
        "smallImg": '/images/7.jpg',
        "name": "Paté",
        "images": ['/images/7.jpg'],
        "descr": "",
    }
}